plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.14'
    id 'maven-publish'
}

apply from: 'gradle/common.gradle'

dependencies {
    // To change the versions see the versions/<mc>.properties files
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}
